return {
  {
    "folke/which-key.nvim",
    opts = {
      preset = "helix",
      spec = {
        {
          mode = { "n", "x" },
          { "<leader><tab>", group = "标签页" },
          { "<leader>b", group = "缓冲区", expand = function() return require("which-key.extras").expand.buf() end },
          { "<leader>c", group = "代码" },
          { "<leader>d", group = "调试" },
          { "<leader>dp", group = "性能分析" },
          { "<leader>f", group = "文件/查找" },
          { "<leader>g", group = "Git" },
          { "<leader>gd", group = "Diff 工具" },
          { "<leader>o", group = "Overseer" },
          { "<leader>a", group = "AI/OpenCode" },
          { "<leader>ap", group = "prompts" },
          { "<leader>as", group = "会话" },
          { "<leader>av", group = "视图" },
          { "<leader>t", group = "测试" },
          { "<leader>gh", group = "代码块" },
          { "<leader>q", group = "退出/会话" },
          { "<leader>s", group = "搜索" },
          { "<leader>sn", group = "消息" },
          { "<leader>u", group = "界面" },
          { "<leader>w", group = "窗口", proxy = "<c-w>", expand = function() return require("which-key.extras").expand.win() end },
          { "<leader>x", group = "诊断/快速修复" },
          { "[", group = "上一个" },
          { "]", group = "下一个" },
          { "g", group = "跳转 / operator" },
          { "go", desc = "→ OpenCode operator" },
          { "gs", group = "环绕" },
          { "z", group = "折叠" },
        },
      },
    },
  },
}
