return {
  {
    "folke/which-key.nvim",
    opts = {
      replace = {
        desc = {
          { "<Plug>%(?(.*)%)?", "%1" },
          { "^%+", "" },
          { "<[cC]md>", "" },
          { "<[cC][rR]>", "" },
          { "<[sS]ilent>", "" },
          { "^lua%s+", "" },
          { "^call%s+", "" },
          { "^:%s*", "" },
          { "%<leader>", "" },

          { "^buffer$", "缓冲区" },
          { "^buffers$", "缓冲区" },
          { "^code$", "代码" },
          { "^debug$", "调试" },
          { "^diagnostics$", "诊断" },
          { "^diagnostics/quickfix$", "诊断/快速修复" },
          { "^file$", "文件" },
          { "^file/find$", "文件/查找" },
          { "^find$", "查找" },
          { "^fold$", "折叠" },
          { "^git$", "Git" },
          { "^goto$", "跳转" },
          { "^hunks$", "代码块" },
          { "^next$", "下一个" },
          { "^prev$", "上一个" },
          { "^profiler$", "性能分析" },
          { "^quit/session$", "退出/会话" },
          { "^search$", "搜索" },
          { "^surround$", "环绕" },
          { "^tabs$", "标签页" },
          { "^ui$", "界面" },
          { "^windows$", "窗口" },

          { "Switch to Other Buffer", "切换到上一个缓冲区" },
          { "Delete Buffer", "删除缓冲区" },
          { "Delete Other Buffers", "删除其他缓冲区" },
          { "Delete Invisible Buffers", "删除不可见缓冲区" },
          { "Delete Buffer and Window", "删除缓冲区和窗口" },
          { "Toggle Pin", "固定/取消固定" },
          { "Delete Non%-Pinned Buffers", "删除未固定的缓冲区" },
          { "Delete Buffers to the Right", "删除右侧缓冲区" },
          { "Delete Buffers to the Left", "删除左侧缓冲区" },
          { "Pick Buffer", "选择缓冲区" },
          { "Prev Buffer", "上一个缓冲区" },
          { "Next Buffer", "下一个缓冲区" },
          { "Move buffer prev", "缓冲区左移" },
          { "Move buffer next", "缓冲区右移" },

          { "Last Tab", "最后一个标签页" },
          { "Close Other Tabs", "关闭其他标签页" },
          { "First Tab", "第一个标签页" },
          { "New Tab", "新建标签页" },
          { "Next Tab", "下一个标签页" },
          { "Close Tab", "关闭标签页" },
          { "Previous Tab", "上一个标签页" },

          { "Lsp Info", "LSP 信息" },
          { "Code Action", "代码操作" },
          { "Run Codelens", "运行 Codelens" },
          { "Refresh & Display Codelens", "刷新并显示 Codelens" },
          { "Rename File", "重命名文件" },
          { "^Rename$", "重命名" },
          { "Source Action", "源代码操作" },
          { "Organize Imports", "组织导入" },
          { "^Format$", "格式化" },
          { "Format Injected Langs", "格式化注入语言" },
          { "Format selection or buffer", "格式化选区或缓冲区" },
          { "Mason", "Mason (LSP 管理器)" },
          { "Symbols %(Trouble%)", "符号列表 (Trouble)" },
          { "LSP references/definitions/%.%.%.", "LSP 引用/定义/... (Trouble)" },
          { "Line Diagnostics", "行诊断信息" },

          { "Toggle Profiler Scratch Buffer", "性能分析临时缓冲区" },
          { "Toggle Auto Format %(Global%)", "切换自动格式化 (全局)" },
          { "Toggle Auto Format %(Buffer%)", "切换自动格式化 (缓冲区)" },
          { "Toggle Spelling", "切换拼写检查" },
          { "Toggle Wrap", "切换自动换行" },
          { "Toggle Relative Number", "切换相对行号" },
          { "Toggle Line Numbers", "切换行号" },
          { "Toggle Conceal Level", "切换隐藏级别" },
          { "Toggle Tabline", "切换标签栏" },
          { "Toggle Treesitter Highlight", "切换语法高亮 (Treesitter)" },
          { "Toggle Dark Background", "切换深色背景" },
          { "Toggle Dimming", "切换暗淡效果" },
          { "Toggle Animations", "切换动画效果" },
          { "Toggle Indent Guides", "切换缩进线" },
          { "Toggle Smooth Scroll", "切换平滑滚动" },
          { "Toggle Inlay Hints", "切换内联提示" },
          { "Toggle Git Signs", "切换 Git 标记" },
          { "Toggle Zoom Mode", "切换缩放窗口" },
          { "Toggle Zen Mode", "切换禅模式" },
          { "Toggle Profiler$", "切换性能分析" },
          { "Toggle Profiler Highlights", "切换性能分析高亮" },

          { "New File", "新建文件" },
          { "Terminal %(cwd%)", "终端 (当前目录)" },
          { "Terminal %(Root Dir%)", "终端 (项目根目录)" },
          { "Hide Terminal", "隐藏终端" },
          { "Find Files %(Root Dir%)", "查找文件 (项目根目录)" },
          { "Find Files %(cwd%)", "查找文件 (当前目录)" },
          { "Find Files %(git%-files%)", "查找文件 (Git)" },
          { "Find Config File", "查找配置文件" },
          { "Grep %(Root Dir%)", "全局搜索 (项目根目录)" },
          { "Grep %(cwd%)", "全局搜索 (当前目录)" },
          { "Grep Open Buffers", "搜索已打开缓冲区" },
          { "Command History", "命令历史" },
          { "^Buffers$", "缓冲区列表" },
          { "Buffers %(all%)", "缓冲区列表 (全部)" },
          { "^Recent$", "最近文件" },
          { "Recent %(cwd%)", "最近文件 (当前目录)" },
          { "^Projects$", "项目列表" },
          { "Explorer Snacks %(root dir%)", "文件浏览器 (项目根目录)" },
          { "Explorer Snacks %(cwd%)", "文件浏览器 (当前目录)" },
          { "Open cwd Directory", "打开当前目录" },
          { "Switch Buffer", "切换缓冲区" },

          { "Lazygit %(Root Dir%)", "Lazygit (项目根目录)" },
          { "Lazygit %(cwd%)", "Lazygit (当前目录)" },
          { "Git Log %(cwd%)", "Git 日志 (当前目录)" },
          { "Git Blame Line", "Git 当前行溯源" },
          { "Git Current File History", "Git 当前文件历史" },
          { "Git Log$", "Git 日志" },
          { "Git Browse %(open%)", "在浏览器中打开 (Git)" },
          { "Git Browse %(copy%)", "复制链接 (Git)" },
          { "Commits", "提交记录" },
          { "Git Status", "Git 状态" },
          { "^Status$", "Git 状态" },
          { "Git Stash", "Git 暂存" },
          { "Git Diff %(files%)", "Git 差异 (文件)" },
          { "Git Diff %(hunks%)", "Git 差异 (代码块)" },
          { "Git Diff %(origin%)", "Git 差异 (远程)" },
          { "GitHub Issues %(open%)", "GitHub Issues (未关闭)" },
          { "GitHub Issues %(all%)", "GitHub Issues (全部)" },
          { "GitHub Pull Requests %(open%)", "GitHub PR (未关闭)" },
          { "GitHub Pull Requests %(all%)", "GitHub PR (全部)" },
          { "Stage Hunk", "暂存代码块" },
          { "Reset Hunk", "重置代码块" },
          { "Stage Buffer", "暂存整个缓冲区" },
          { "Undo Stage Hunk", "撤销暂存代码块" },
          { "Reset Buffer", "重置整个缓冲区" },
          { "Preview Hunk Inline", "预览代码块 (内联)" },
          { "Blame Line", "行溯源" },
          { "Blame Buffer", "缓冲区溯源" },
          { "Diff This$", "对比当前版本" },
          { "Diff This ~", "对比上一版本" },
          { "Next Hunk", "下一个代码块" },
          { "Prev Hunk", "上一个代码块" },
          { "Last Hunk", "最后一个代码块" },
          { "First Hunk", "第一个代码块" },

          { "Quit All", "全部退出" },
          { "Quit buffer", "退出缓冲区" },
          { "Restore Session", "恢复会话" },
          { "Select Session", "选择会话" },
          { "Restore Last Session", "恢复上次会话" },
          { "Don't Save Current Session", "不保存当前会话" },

          { "Autocmds", "自动命令" },
          { "Auto Commands", "自动命令" },
          { "Buffer Lines", "缓冲区内容搜索" },
          { "^Commands$", "命令列表" },
          { "Buffer Diagnostics", "缓冲区诊断" },
          { "^Diagnostics$", "诊断信息" },
          { "Help Pages", "帮助文档" },
          { "^Highlights$", "高亮组" },
          { "Search Highlight Groups", "搜索高亮组" },
          { "^Icons$", "图标" },
          { "^Jumps$", "跳转列表" },
          { "Jumplist", "跳转列表" },
          { "^Keymaps$", "快捷键映射" },
          { "Key Maps", "快捷键映射" },
          { "Location List", "位置列表" },
          { "Man Pages", "Man 手册" },
          { "^Marks$", "标记" },
          { "Jump to Mark", "跳转到标记" },
          { "^Resume$", "恢复上次搜索" },
          { "Quickfix List", "快速修复列表" },
          { "Previous Quickfix", "上一个快速修复" },
          { "Next Quickfix", "下一个快速修复" },
          { "Word %(Root Dir%)", "搜索当前词 (项目根目录)" },
          { "Word %(cwd%)", "搜索当前词 (当前目录)" },
          { "Visual selection or word %(Root Dir%)", "搜索选区或当前词 (项目根目录)" },
          { "Visual selection or word %(cwd%)", "搜索选区或当前词 (当前目录)" },
          { "Selection %(Root Dir%)", "搜索选区 (项目根目录)" },
          { "Selection %(cwd%)", "搜索选区 (当前目录)" },
          { "Search History", "搜索历史" },
          { "^Registers$", "寄存器" },
          { "^Options$", "选项" },
          { "Colorschemes", "配色方案" },
          { "Colorscheme with Preview", "配色方案 (预览)" },
          { "Undotree", "撤销历史树" },
          { "Search for Plugin Spec", "搜索插件定义" },
          { "^Todo$", "待办事项" },
          { "Todo/Fix/Fixme", "待办/修复/Fixme" },

          { "LSP Symbols", "LSP 符号" },
          { "LSP Workspace Symbols", "LSP 工作区符号" },
          { "Goto Symbol", "跳转到符号" },
          { "Goto Symbol %(Workspace%)", "跳转到符号 (工作区)" },
          { "C%[a%]lls Incoming", "调用方 (谁调用了它)" },
          { "C%[a%]lls Outgoing", "被调用方 (它调用了谁)" },

          { "Noice Last Message", "最后一条消息" },
          { "Noice History", "消息历史" },
          { "Noice All", "所有消息" },
          { "Noice Picker %(Telescope/FzfLua%)", "消息选择器" },
          { "Dismiss All", "清除所有消息" },
          { "Redirect Cmdline", "重定向命令行" },
          { "Scroll Forward", "向前滚动" },
          { "Scroll Backward", "向后滚动" },

          { "Redraw / Clear hlsearch / Diff Update", "重绘/清除搜索高亮" },
          { "Inspect Pos", "检查位置" },
          { "Inspect Tree", "检查语法树" },
          { "Dismiss All Notifications", "清除所有通知" },
          { "Notification History", "通知历史" },

          { "Diagnostics %(Trouble%)", "诊断列表 (Trouble)" },
          { "Buffer Diagnostics %(Trouble%)", "缓冲区诊断 (Trouble)" },
          { "Location List %(Trouble%)", "位置列表 (Trouble)" },
          { "Quickfix List %(Trouble%)", "快速修复列表 (Trouble)" },
          { "Todo %(Trouble%)", "待办事项 (Trouble)" },
          { "Todo/Fix/Fixme %(Trouble%)", "待办/修复/Fixme (Trouble)" },

          { "Split Window Below", "水平分屏" },
          { "Split Window Right", "垂直分屏" },
          { "Delete Window", "关闭窗口" },

          { "Keywordprg", "查看关键字文档" },
          { "^Lazy$", "Lazy (插件管理器)" },
          { "LazyVim Changelog", "LazyVim 更新日志" },
          { "Toggle Scratch Buffer", "临时缓冲区" },
          { "Select Scratch Buffer", "选择临时缓冲区" },
          { "Buffer Keymaps %(which%-key%)", "缓冲区快捷键 (which-key)" },
          { "Search and Replace", "搜索并替换" },
          { "Run Lua", "运行 Lua" },
          { "Manage LazyVim extras", "管理 LazyVim 扩展" },
          { "Load all plugins and run :checkhealth", "加载所有插件并运行检查" },
          { "Show info about the formatters", "显示格式化工具信息" },
          { "LazyVim roots for the current buffer", "当前缓冲区的 LazyVim 根目录" },
          { "LazyVim extras", "LazyVim 扩展" },
          { "User extras", "用户扩展" },

          { "Go to Left Window", "跳转到左侧窗口" },
          { "Go to Lower Window", "跳转到下方窗口" },
          { "Go to Upper Window", "跳转到上方窗口" },
          { "Go to Right Window", "跳转到右侧窗口" },
          { "Increase Window Height", "增加窗口高度" },
          { "Decrease Window Height", "减少窗口高度" },
          { "Decrease Window Width", "减少窗口宽度" },
          { "Increase Window Width", "增加窗口宽度" },
          { "Move Down", "向下移动行" },
          { "Move Up", "向上移动行" },
          { "Escape and Clear hlsearch", "退出并清除搜索高亮" },
          { "Save File", "保存文件" },
          { "Add Comment Below", "在下方添加注释" },
          { "Add Comment Above", "在上方添加注释" },
          { "Goto Definition", "跳转到定义" },
          { "^References$", "查看引用" },
          { "Goto Implementation", "跳转到实现" },
          { "Goto T[y]pe Definition", "跳转到类型定义" },
          { "Goto Declaration", "跳转到声明" },
          { "^Hover$", "悬浮文档" },
          { "Signature Help", "函数签名帮助" },
          { "^Flash$", "快速跳转 (Flash)" },
          { "Flash Treesitter", "语法跳转 (Flash)" },
          { "Remote Flash", "远程 Flash" },
          { "Treesitter Search", "语法搜索" },
          { "Treesitter Incremental Selection", "语法增量选择" },
          { "Toggle Flash Search", "切换 Flash 搜索" },

          { "Next Todo Comment", "下一个待办注释" },
          { "Previous Todo Comment", "上一个待办注释" },
          { "Next Diagnostic", "下一个诊断" },
          { "Prev Diagnostic", "上一个诊断" },
          { "Next Error", "下一个错误" },
          { "Prev Error", "上一个错误" },
          { "Next Warning", "下一个警告" },
          { "Prev Warning", "上一个警告" },
          { "Next Trouble/Quickfix Item", "下一个 Trouble/Quickfix 项" },
          { "Previous Trouble/Quickfix Item", "上一个 Trouble/Quickfix 项" },
          { "Next Reference$", "下一个引用" },
          { "Prev Reference$", "上一个引用" },
          { "Next Search Result", "下一个搜索结果" },
          { "Prev Search Result", "上一个搜索结果" },
          { "Window Hydra Mode %(which%-key%)", "窗口管理模式" },
          { "Open with system app", "用系统应用打开" },

          { "Find File", "查找文件" },
          { "Find Text", "查找文本" },
          { "Recent Files", "最近文件" },
          { "^Config$", "配置" },
          { "Lazy Extras", "Lazy 扩展" },
          { "^Quit$", "退出" },
        },
      },
      spec = {
        { "<leader><tab>", group = "标签页" },
        { "<leader>b", group = "缓冲区" },
        { "<leader>c", group = "代码" },
        { "<leader>d", group = "调试" },
        { "<leader>dp", group = "性能分析" },
        { "<leader>f", group = "文件/查找" },
        { "<leader>g", group = "Git" },
        { "<leader>gh", group = "代码块" },
        { "<leader>q", group = "退出/会话" },
        { "<leader>s", group = "搜索" },
        { "<leader>sn", group = "消息" },
        { "<leader>u", group = "界面" },
        { "<leader>x", group = "诊断/快速修复" },
        { "<leader>w", group = "窗口" },
        { "[", group = "上一个" },
        { "]", group = "下一个" },
        { "g", group = "跳转" },
        { "gs", group = "环绕" },
        { "z", group = "折叠" },
      },
    },
  },
}