return {
  {
    "folke/which-key.nvim",
    opts = {
      preset = "helix",
      spec = {
        {
          mode = { "n", "x" },
          -- groups
          { "<leader><tab>", group = "标签页" },
          { "<leader>b", group = "缓冲区", expand = function() return require("which-key.extras").expand.buf() end },
          { "<leader>c", group = "代码" },
          { "<leader>d", group = "调试" },
          { "<leader>dp", group = "性能分析" },
          { "<leader>f", group = "文件/查找" },
          { "<leader>g", group = "Git" },
          { "<leader>gh", group = "代码块" },
          { "<leader>q", group = "退出/会话" },
          { "<leader>s", group = "搜索" },
          { "<leader>sn", group = "消息" },
          { "<leader>u", group = "界面" },
          { "<leader>w", group = "窗口", proxy = "<c-w>", expand = function() return require("which-key.extras").expand.win() end },
          { "<leader>x", group = "诊断/快速修复" },
          { "[", group = "上一个" },
          { "]", group = "下一个" },
          { "g", group = "跳转" },
          { "gs", group = "环绕" },
          { "z", group = "折叠" },

          -- flash
          { "s", desc = "快速跳转 (Flash)" },
          { "S", desc = "语法跳转 (Flash)", mode = { "n", "o", "x" } },
          { "r", desc = "远程 Flash", mode = "o" },
          { "R", desc = "语法搜索", mode = { "o", "x" } },
          { "<c-s>", desc = "切换 Flash 搜索", mode = "c" },
          { "<c-space>", desc = "语法增量选择", mode = { "n", "o", "x" } },

          -- window navigation
          { "<C-h>", desc = "跳转到左侧窗口" },
          { "<C-j>", desc = "跳转到下方窗口" },
          { "<C-k>", desc = "跳转到上方窗口" },
          { "<C-l>", desc = "跳转到右侧窗口" },
          { "<C-Up>", desc = "增加窗口高度" },
          { "<C-Down>", desc = "减少窗口高度" },
          { "<C-Left>", desc = "减少窗口宽度" },
          { "<C-Right>", desc = "增加窗口宽度" },

          -- misc
          { "gx", desc = "用系统应用打开" },

          -- bufferline
          { "<leader>bp", desc = "固定/取消固定" },
          { "<leader>bP", desc = "删除未固定的缓冲区" },
          { "<leader>br", desc = "删除右侧缓冲区" },
          { "<leader>bl", desc = "删除左侧缓冲区" },
          { "<leader>bj", desc = "选择缓冲区" },
          { "<leader>bd", desc = "删除缓冲区" },
          { "<leader>bD", desc = "删除缓冲区和窗口" },
          { "<leader>bo", desc = "删除其他缓冲区" },
          { "<leader>bb", desc = "切换到上一个缓冲区" },
          { "<leader>`", desc = "切换到上一个缓冲区" },
          { "<S-h>", desc = "上一个缓冲区" },
          { "<S-l>", desc = "下一个缓冲区" },
          { "[b", desc = "上一个缓冲区" },
          { "]b", desc = "下一个缓冲区" },
          { "[B", desc = "缓冲区左移" },
          { "]B", desc = "缓冲区右移" },

          -- which-key
          { "<leader>?", desc = "缓冲区快捷键 (which-key)" },
          { "<c-w><space>", desc = "窗口管理模式" },

          -- snacks
          { "<leader>,", desc = "缓冲区列表" },
          { "<leader>/", desc = "全局搜索 (项目根目录)" },
          { "<leader>:", desc = "命令历史" },
          { "<leader><space>", desc = "查找文件 (项目根目录)" },
          { "<leader>n", desc = "通知历史" },
          { "<leader>.", desc = "临时缓冲区" },
          { "<leader>S", desc = "选择临时缓冲区" },

          -- find
          { "<leader>fb", desc = "缓冲区列表" },
          { "<leader>fB", desc = "缓冲区列表 (全部)" },
          { "<leader>fc", desc = "查找配置文件" },
          { "<leader>ff", desc = "查找文件 (项目根目录)" },
          { "<leader>fF", desc = "查找文件 (当前目录)" },
          { "<leader>fg", desc = "查找文件 (Git)" },
          { "<leader>fr", desc = "最近文件" },
          { "<leader>fR", desc = "最近文件 (当前目录)" },
          { "<leader>fp", desc = "项目列表" },

          -- git
          { "<leader>gd", desc = "Git 差异 (代码块)" },
          { "<leader>gD", desc = "Git 差异 (远程)" },
          { "<leader>gs", desc = "Git 状态" },
          { "<leader>gS", desc = "Git 暂存" },
          { "<leader>gi", desc = "GitHub Issues (未关闭)" },
          { "<leader>gI", desc = "GitHub Issues (全部)" },
          { "<leader>gp", desc = "GitHub PR (未关闭)" },
          { "<leader>gP", desc = "GitHub PR (全部)" },
          { "<leader>gg", desc = "Lazygit (项目根目录)" },
          { "<leader>gG", desc = "Lazygit (当前目录)" },
          { "<leader>gL", desc = "Git 日志 (当前目录)" },
          { "<leader>gl", desc = "Git 日志" },
          { "<leader>gb", desc = "Git 当前行溯源" },
          { "<leader>gf", desc = "Git 当前文件历史" },
          { "<leader>gB", desc = "在浏览器中打开 (Git)" },
          { "<leader>gY", desc = "复制链接 (Git)" },

          -- git hunks
          { "<leader>ghs", desc = "暂存代码块" },
          { "<leader>ghr", desc = "重置代码块" },
          { "<leader>ghS", desc = "暂存整个缓冲区" },
          { "<leader>ghu", desc = "撤销暂存代码块" },
          { "<leader>ghR", desc = "重置整个缓冲区" },
          { "<leader>ghp", desc = "预览代码块 (内联)" },
          { "<leader>ghb", desc = "行溯源" },
          { "<leader>ghB", desc = "缓冲区溯源" },
          { "<leader>ghd", desc = "对比当前版本" },
          { "<leader>ghD", desc = "对比上一版本" },

          -- search
          { "<leader>sb", desc = "缓冲区内容搜索" },
          { "<leader>sB", desc = "搜索已打开缓冲区" },
          { "<leader>sg", desc = "全局搜索 (项目根目录)" },
          { "<leader>sG", desc = "全局搜索 (当前目录)" },
          { "<leader>sp", desc = "搜索插件定义" },
          { "<leader>sw", desc = "搜索选区或当前词 (项目根目录)" },
          { "<leader>sW", desc = "搜索选区或当前词 (当前目录)" },
          { '<leader>s"', desc = "寄存器" },
          { "<leader>s/", desc = "搜索历史" },
          { "<leader>sa", desc = "自动命令" },
          { "<leader>sc", desc = "命令历史" },
          { "<leader>sC", desc = "命令列表" },
          { "<leader>sd", desc = "诊断信息" },
          { "<leader>sD", desc = "缓冲区诊断" },
          { "<leader>sh", desc = "帮助文档" },
          { "<leader>sH", desc = "高亮组" },
          { "<leader>si", desc = "图标" },
          { "<leader>sj", desc = "跳转列表" },
          { "<leader>sk", desc = "快捷键映射" },
          { "<leader>sl", desc = "位置列表" },
          { "<leader>sM", desc = "Man 手册" },
          { "<leader>sm", desc = "标记" },
          { "<leader>sR", desc = "恢复上次搜索" },
          { "<leader>sq", desc = "快速修复列表" },
          { "<leader>su", desc = "撤销历史树" },
          { "<leader>sr", desc = "搜索并替换" },

          -- search / noice
          { "<leader>snl", desc = "最后一条消息" },
          { "<leader>snh", desc = "消息历史" },
          { "<leader>sna", desc = "所有消息" },
          { "<leader>snd", desc = "清除所有消息" },
          { "<leader>snt", desc = "消息选择器" },
          { "<S-Enter>", desc = "重定向命令行", mode = "c" },
          { "<c-f>", desc = "向前滚动", mode = { "i", "n", "s" } },
          { "<c-b>", desc = "向后滚动", mode = { "i", "n", "s" } },

          -- search / todo
          { "<leader>st", desc = "待办事项" },
          { "<leader>sT", desc = "待办/修复/Fixme" },

          -- search / lsp symbols
          { "<leader>ss", desc = "LSP 符号" },
          { "<leader>sS", desc = "LSP 工作区符号" },

          -- LSP
          { "<leader>cl", desc = "LSP 信息" },
          { "gd", desc = "跳转到定义" },
          { "gr", desc = "查看引用" },
          { "gI", desc = "跳转到实现" },
          { "gy", desc = "跳转到类型定义" },
          { "gD", desc = "跳转到声明" },
          { "K", desc = "悬浮文档" },
          { "gK", desc = "函数签名帮助" },
          { "<c-k>", desc = "函数签名帮助", mode = "i" },
          { "<leader>ca", desc = "代码操作" },
          { "<leader>cc", desc = "运行 Codelens" },
          { "<leader>cC", desc = "刷新并显示 Codelens" },
          { "<leader>cR", desc = "重命名文件" },
          { "<leader>cr", desc = "重命名" },
          { "<leader>cA", desc = "源代码操作" },
          { "<leader>co", desc = "组织导入" },
          { "<leader>cm", desc = "Mason (LSP 管理器)" },
          { "<leader>cf", desc = "格式化" },
          { "<leader>cF", desc = "格式化注入语言" },
          { "<leader>cs", desc = "符号列表 (Trouble)" },
          { "<leader>cS", desc = "LSP 引用/定义/... (Trouble)" },
          { "]]", desc = "下一个引用" },
          { "[[", desc = "上一个引用" },
          { "<a-n>", desc = "下一个引用" },
          { "<a-p>", desc = "上一个引用" },
          { "gai", desc = "调用方 (谁调用了它)" },
          { "gao", desc = "被调用方 (它调用了谁)" },

          -- diagnostics / trouble
          { "<leader>xx", desc = "诊断列表 (Trouble)" },
          { "<leader>xX", desc = "缓冲区诊断 (Trouble)" },
          { "<leader>xL", desc = "位置列表 (Trouble)" },
          { "<leader>xQ", desc = "快速修复列表 (Trouble)" },
          { "<leader>xt", desc = "待办事项 (Trouble)" },
          { "<leader>xT", desc = "待办/修复/Fixme (Trouble)" },
          { "[q", desc = "上一个快速修复" },
          { "]q", desc = "下一个快速修复" },

          -- diagnostics / line
          { "<leader>cd", desc = "行诊断信息" },

          -- diagnostics / navigation
          { "]t", desc = "下一个待办注释" },
          { "[t", desc = "上一个待办注释" },
          { "]h", desc = "下一个代码块" },
          { "[h", desc = "上一个代码块" },
          { "]H", desc = "最后一个代码块" },
          { "[H", desc = "第一个代码块" },
          { "]d", desc = "下一个诊断" },
          { "[d", desc = "上一个诊断" },
          { "]e", desc = "下一个错误" },
          { "[e", desc = "上一个错误" },
          { "]w", desc = "下一个警告" },
          { "[w", desc = "上一个警告" },

          -- search results
          { "n", desc = "下一个搜索结果" },
          { "N", desc = "上一个搜索结果" },

          -- ui toggles (Snacks.toggle)
          { "<leader>uf", desc = "切换自动格式化 (全局)" },
          { "<leader>uF", desc = "切换自动格式化 (缓冲区)" },
          { "<leader>us", desc = "切换拼写检查" },
          { "<leader>uw", desc = "切换自动换行" },
          { "<leader>uL", desc = "切换相对行号" },
          { "<leader>ul", desc = "切换行号" },
          { "<leader>uc", desc = "切换隐藏级别" },
          { "<leader>uA", desc = "切换标签栏" },
          { "<leader>uT", desc = "切换语法高亮 (Treesitter)" },
          { "<leader>ub", desc = "切换深色背景" },
          { "<leader>uD", desc = "切换暗淡效果" },
          { "<leader>ua", desc = "切换动画效果" },
          { "<leader>ug", desc = "切换缩进线" },
          { "<leader>uS", desc = "切换平滑滚动" },
          { "<leader>uh", desc = "切换内联提示" },
          { "<leader>ud", desc = "切换诊断" },
          { "<leader>wm", desc = "切换缩放窗口" },
          { "<leader>uZ", desc = "切换缩放窗口" },
          { "<leader>uz", desc = "切换禅模式" },
          { "<leader>uC", desc = "配色方案 (预览)" },
          { "<leader>un", desc = "清除所有通知" },
          { "<leader>ur", desc = "重绘/清除搜索高亮" },
          { "<leader>ui", desc = "检查位置" },
          { "<leader>uI", desc = "检查语法树" },
          { "<leader>uG", desc = "切换 Git 标记" },

          -- profiler toggles
          { "<leader>dpp", desc = "切换性能分析" },
          { "<leader>dph", desc = "切换性能分析高亮" },
          { "<leader>dps", desc = "性能分析临时缓冲区" },

          -- quit / session
          { "<leader>qq", desc = "全部退出" },
          { "<leader>qs", desc = "恢复会话" },
          { "<leader>qS", desc = "选择会话" },
          { "<leader>ql", desc = "恢复上次会话" },
          { "<leader>qd", desc = "不保存当前会话" },

          -- tabs
          { "<leader><tab>l", desc = "最后一个标签页" },
          { "<leader><tab>o", desc = "关闭其他标签页" },
          { "<leader><tab>f", desc = "第一个标签页" },
          { "<leader><tab><tab>", desc = "新建标签页" },
          { "<leader><tab>]", desc = "下一个标签页" },
          { "<leader><tab>d", desc = "关闭标签页" },
          { "<leader><tab>[", desc = "上一个标签页" },

          -- windows
          { "<leader>w-", desc = "水平分屏" },
          { "<leader>w|", desc = "垂直分屏" },
          { "<leader>wd", desc = "关闭窗口" },

          -- terminal
          { "<leader>ft", desc = "终端 (项目根目录)" },
          { "<leader>fT", desc = "终端 (当前目录)" },
          { "<c-/>", desc = "终端 (项目根目录)", mode = { "n", "t" } },

          -- misc
          { "<leader>e", desc = "文件浏览器 (项目根目录)" },
          { "<leader>E", desc = "文件浏览器 (当前目录)" },
          { "<leader>l", desc = "Lazy (插件管理器)" },
          { "<leader>L", desc = "LazyVim 更新日志" },
          { "<leader>fn", desc = "新建文件" },
          { "<leader>K", desc = "查看关键字文档" },
          { "<C-s>", desc = "保存文件", mode = { "i", "x", "n", "s" } },
          { "<esc>", desc = "退出并清除搜索高亮", mode = { "i", "n", "s" } },
          { "gco", desc = "在下方添加注释" },
          { "gcO", desc = "在上方添加注释" },
          { "<A-j>", desc = "向下移动行", mode = { "n", "i", "v" } },
          { "<A-k>", desc = "向上移动行", mode = { "n", "i", "v" } },

          -- quickfix / location
          { "<leader>xq", desc = "快速修复列表" },
          { "<leader>xl", desc = "位置列表" },

          -- dashboard keys are translated via snacks dashboard opts override in ui.lua
        },
      },
    },
  },
}
